[package]
name = "view_tst"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
windows = []

[target.'cfg(unix)'.dependencies]
ext4-view = { version = "0.9.1", features = ["std"] }
